int makemonst ( int );
void positionplayer ( void );
void fl_recalculate_armor_class ( void );
void quit ( void );
int more ( char );
void enchantarmor ( void );
void enchweapon ( void );
int nearbymonst ( void );
int stealsomething ( void );
int emptyhanded ( void );
void creategem ( void );
void adjustcvalues ( int, int );
int getpassword ( void );
char getyn ( void );
int packweight ( void );
