void setupvt100 ( void );
void clearvt100 ( void );
char ttgetch ( void );
void scbr ( void );
void sncbr ( void );
void lprintf ( const char *, ... );
void fl_display_message ( const char *, ... );
void lprint ( int );
void lprc ( char );
void lwrite ( char *, int );
char lgetc ( void );
int larint ( void );
void lrfill ( char *, int );
char *lgetw ( void );
char *lgetl ( void );
int lcreat ( char * );
int lopen ( char * );
int lappend ( char * );
void lrclose ( void );
void lwclose ( void );
void fl_termcap_cursor_position ( int, int );
void init_term ( void );
void cl_line ( int, int );
void cl_up ( int, int );
void cl_dn ( int, int );
void lstandout ( const char* );
void set_score_output ( void );
void fl_output_buffer_flush ( void );
void lflushall ( void );
char *tmcapcnv ( char *, char * );
void enter_name ( void );

/* size of the lgetw() and lgetl() buffer */
inline const int LINBUFSIZE = 128;